### ISSUE TITLE
How you Stitching the panorama？

### ISSUE THREAD

**Issue by dxcweb** [ondras/pano.zarovi.cz#1]

**Comment by ondras** [comment]
Hi,

my panoramas are taken with a drone (dji mini 3 pro) and the drone software automatically stitches them. You can, however, do that yourself; you need a 2:1 equirectangular-projected image. I believe [Hugin](https://hugin.sourceforge.io/) can do that and there might be [many](https://untamedscience.com/blog/creating-360-degree-images/) [other](http://paulbourke.net/panorama/sphericalpano/) [approaches...](https://www.google.com/search?client=firefox-b-d&q=how+to+create+equirectangular+panorama)
